repos:
  # Ruff for linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.15
    hooks:
      # Run the linter
      - id: ruff
        args: [ --fix ]
      # Run the formatter
      - id: ruff-format

  # Additional useful hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Check for merge conflicts
      - id: check-merge-conflict
      # Check YAML files
      - id: check-yaml
      # Check TOML files
      - id: check-toml
      # Check JSON files
      - id: check-json
      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict
      # Remove trailing whitespace
      - id: trailing-whitespace
      # Ensure files end with a newline
      - id: end-of-file-fixer
      # Check for large files
      - id: check-added-large-files
        args: ['--maxkb=1000']

# Configuration for the pre-commit CI service
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
